- name: Update Personal Site
  hosts: personal-site
  become: true
  vars_files:
    - secrets.yml
  gather_facts: false
  tasks:
    - name: Pull latest content
      git:
        repo: 'https://github.com/cgreggescalante/cgreggescalante'
        dest: sources/
        version: master
        force: yes

    - name: Get Dependencies
      shell: cd sources && /usr/local/go/bin/go mod tidy

    - name: Build project
      shell: cd sources && /usr/local/go/bin/go build main.go

    - name: Restart service
      shell: systemctl restart go-service
