- name: Find files in /etc/nginx
  find:
    paths: /etc/nginx/
    recurse: yes
    file_type: any
  register: nginx_config_files

- name: Remove all files from /etc/nginx
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ nginx_config_files.files }}"
  when: nginx_config_files.matched > 0
  ignore_errors: yes

- name: Add mime.types
  copy:
    src: ../mime.types
    dest: /etc/nginx/mime.types

- name: Format Nginx config
  template:
    src: ../nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Test Nginx config
  command: nginx -t

- name: Reload Nginx
  command: nginx -s reload