- name: Create LXC Container for Nginx Reverse Proxy
  hosts: pve1
  become: true
  vars_files:
    - ../secrets.yml
  vars:
    node: pve1
    api_user: ansible@pam
    api_token_id: ansible-token
    api_host: pve1
    cores: 1
    vmid: 100
    memory: 1024
    swap: 512
    rootfs: local-lvm:8
    hostname: reverse-proxy
    net0: "name=eth0,bridge=vmbr0,ip=192.168.33.100/24,gw=192.168.33.1"
    ostemplate: 'local:vztmpl/ubuntu-20.04-standard_20.04-1_amd64.tar.gz'
  tasks:
    - debug:
        var: api_token_secret
    - name: Create LXC Container
      import_tasks: tasks/create_lxc.yml

- name: Install Nginx Reverse Proxy
  hosts: reverse-proxy
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: Install Dependencies
      apt:
        name:
          - git
          - nginx
          - certbot
          - python3-certbot-nginx
        state: present
        update_cache: yes

    - name: Add Nginx User
      user:
        name: nginx

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Request SSL certificate for cgreggescalante.com
      command: certbot certonly --nginx -d cgreggescalante.com --email conor@johngregg.org --agree-tos --non-interactive
      register: certbot_result
      failed_when: "'Congratulations' not in certbot_result.stdout"

    - name: Request SSL certificate for test.cgreggescalante.com
      command: certbot certonly --nginx -d test.cgreggescalante.com --email conor@johngregg.org --agree-tos --non-interactive
      register: certbot_result
      failed_when: "'Congratulations' not in certbot_result.stdout"

    - name: Update Nginx Reverse Proxy
      import_tasks: tasks/update_reverse_proxy.yml